### ISSUE TITLE
Upgrade to 3.3.7

### ISSUE THREAD

**Issue by maixiu** [Hilzu/bootstrap-grid#3]
Bootstrap is now version 3.3.7
This package should be upgraded according to bootstrap new version.

**Comment by maixiu** [comment]
I can handle this issue, can I have some direction ?

**Comment by Hilzu** [comment]
Bootstrap 3.3.7 has been out since Jul 25, 2016 and version 3.0.1 of this package already uses it so there's nothing to do.
